name: github-actions-test

on: [push]

jobs:
  sample_command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start
        run: echo "start workflow"
      - name: sample command
        run: |
          cat README.md
          ls -al

  sample_rs_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: test
        run: cargo test --all fail_test
        working-directory: rs_sample
